name: Continuous Integration

on: 
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['20.x', '22.x']

    services:
      postgres:
        image: postgres:13  # Versi eksplisit lebih stabil
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: mysecretpassword
          POSTGRES_DB: forumapi_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h localhost -p 5432 -U postgres; do
            echo "Waiting for postgres..."
            sleep 2
          done

      - name: Install dependencies, migrate, and test
        run: |
          npm install
          npm run migrate up
          npm run test
        env:
          CI: true
          HOST: localhost
          PORT: 3000
          PGHOST: localhost
          PGPORT: 5432
          PGUSER: postgres
          PGPASSWORD: mysecretpassword
          PGDATABASE: forumapi_test
          ACCESS_TOKEN_KEY: secret
          REFRESH_TOKEN_KEY: terces
          ACCESS_TOKEN_AGE: 3600
